language: node_js

sudo: required

node_js:
  - '7'

cache:
  directories:
    - $TRAVIS_BUILD_DIR/elm-stuff/build-artifacts
    - $TRAVIS_BUILD_DIR/tests/elm-stuff/build-artifacts

install:
  - npm i elm-format create-elm-app gh-pages -g

script:
  - elm-format --validate src/
  - cd src
  - elm-app make src/Main.elm --output=/dev/null --yes --warn
  - cd ..
  - elm-app test
  - elm-app build