sudo: false

language: elm
elm:
  latest-0.19.1
elm_test:
  0.19.1
elm_format:
  0.8.2

script:
  - bash build.sh

install:
  - npm install -g uglify-js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master