language: elm
elm:
  latest-0.19.1
elm_test:
  0.19.1
elm_format:
  0.8.2

jobs:
  include:
    - stage: test
      script:
        - echo 'Validating'
        - elm-format --validate
        - echo 'Running tests'
        - elm-test
    - stage: deploy
      script:
        - npm install -g create-elm-app
        - elm-app build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: build/
        on:
          branch: master

stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master